# Generated by Django 4.0.6 on 2022-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatat',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
