# Generated by Django 4.0.6 on 2022-08-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatat',
            new_name='avatar',
        ),
    ]
